#!/usr/bin/env bash
# installs nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '24i/location /redirect_me {\n return  https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx reload
