#!/usr/bin/env bash
# This script that loops from 1 to 10 and prints "bad luck" on the 4th and "good luck" on the 8th iteration
i=1
while (( i <= 10 ))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
